### ISSUE TITLE
How does contextual keyword parsing work?

### ISSUE THREAD

**Issue by cr1901** [matklad/fall#7]
I found your excellent [blog post](https://matklad.github.io/2018/06/06/modern-parser-generator.html) on parsing today. It has helped me to (start) get over a wall I've had with parsing in general; that the theory doesn't map well to practice. I found your paragraphs on Lexing especially good, including the linked fall example, but wanted to know more about how to handle context-sensitivity.

>Another interesting lexing problem which arises in practice is context-sensitivity: things like contextual keywords or >> can represent different token types, depending on the surrounding code. To deal with this case nicely, the parser should support token remapping. While most of the tokens appear in the final parse tree as is, the parser should be able to, for example, substitute two > > tokens with a single >>, so that later stages of compilation need not to handle this special case.

Although there's no example for this case, `fall` _does_ handle contextual keywords. So I decided to take a look myself to see how it's implemented. Unfortunately, I got a bit stuck trying to figure out how the parser remapping works.

According to the fall [grammar](https://github.com/matklad/fall/blob/71cd05c6eaa026f692db87d4a8ffe1326706efd4/lang/fall/syntax/src/fall.fall):

```
  // Contextual attribute is required to support contextual keywords.
  // The lexer ignores contextual token and, for example, parses `node`
  // as an identifier. The parser however will remap identifier to the
  // node keyword. You typical don't need `#[contextual]`, but we use
  // it in Fall to avoid clashes with keywords in the target language.
```

I found the specific lexer [code](https://github.com/matklad/fall/blob/71cd05c6eaa026f692db87d4a8ffe1326706efd4/fall/gen/src/generate/codegen.rs#L67) that ignores contextual tokens. I assume the idea is that "the lexing phase will choose a different token type to associate with a contextual token type, and often this will be a plain-old identifier". Is this correct?

At this point, I can't seem to find the equivalent parser code that handles contextual keywords. Could you point me in the right direction? Specifically, _how does `fall` decide whether parser remapping is necessary based on surrounding context of a contextual token_?

(Btw, in the case of the `node` example in the above comment is the idea that "node is a keyword if it's outside braces, and otherwise it's treated as an identifier"?)

**Comment by matklad** [comment]
To be fair, I haven’t touched fall in years, so I don’t remember how everything works.

it seems that you might want to look at https://github.com/matklad/fall/blob/983d267c868566effac1f02a9c72358ad015950a/fall/parse/src/syn_engine/expr.rs#L74

I *think* contextual keywords works by looking at the token text, completely disregarding token type.

More generally, I now think that lexer should treat idents and tokens exactly the same all the time, and it’s parser’s job to forbid particular identifiers.

**Comment by cr1901** [comment]
AFAICT, `parse_contextual_token` is for parsing `.fall` files to generate a parser (forgot to mention that I took a look there as well). But if you don't remember, then I guess I'll look elsewhere. Rust itself uses contextual keywords a lot for backwards-compat (`await` was one I think), but I haven't exactly found a great deal of info how to parse contextual keywords in practice.

>lexer should treat idents and tokens exactly the same all the time.

Well, in this case, I guess you can pass down a "stack" of forbidden identifiers (or other state) based on what grammar rule you're currently parsing. Does "treat idents and tokens exactly the same" handle the `>``>` vs `>>` case as well?

**Comment by cr1901** [comment]
For my immediate needs, I was able to keep the grammar pure LR using LALRPOP and used a [stateful lexer](https://github.com/cr1901/hl2html/blob/main/src/lexer.rs#L8-L11) to handle the context-sensitivity. I also found [this blog post](https://blog.waleedkhan.name/parsing-contextual-keywords) informative, especially the observation that "sometimes contextual keywords can be encoded into the grammar without introducing ambiguity".

Off-topic aside: I need to put this on the backburner for now, but I was linked another one of your [posts](https://rust-analyzer.github.io/blog/2020/09/16/challeging-LR-parsing.html#error-resilience) today as well as a reddit [post](https://www.reddit.com/r/programming/comments/iu2jop/challenging_lr_parsing/g5kfxa8?utm_source=share&utm_medium=web2x&context=3) about how LALRPOP only has error recovery, not resilience. I was wondering if you'd be up to elaborate on that if I send you an email (respond at your leisure/convenience)? I've been playing with LALRPOP to "keep going on error", and I'm not sure I understand what error resilience is.

**Comment by matklad** [comment]
For error resilience, the snippet in https://rust-analyzer.github.io/blog/2020/09/16/challeging-LR-parsing.html#error-resilience is a good example -- although the syntax is broken, the parse tree is reasonable. 

You can see this in action using "show syntax tree" in rust-analyzer -- no matter what garbage I type in, the parser correctly recognizes valid bits of sytnax:

https://user-images.githubusercontent.com/1711539/132487584-a8f9828f-ecba-4e07-b90e-2594eeed20d7.mp4

I haven't seen this level of error resilience in LR parsers.

**Comment by cr1901** [comment]
Cool demo. Kinda makes me want to do the same for Atom, except I'd no idea where to start :).

I guess my question is: Why can't you get some level of error resilience from an LR parser by always returning a valid AST, even on error, and providing information about the invalid nodes (and why they're invalid) out-of-band?

You can then map spans from your error types back to the offending AST nodes during error message generation. You then recreate the "bad parts" of your tree as you desire for the purpose of showing errors and syntax highlighting (?), etc.

**Comment by matklad** [comment]
>Why can't you get some level of error resilience from an LR parser by always returning a valid AST, even on error, and providing information about the invalid nodes (and why they're invalid) out-of-band?

Maybe you can, I just haven't seen this done in practice to a satisfactory level!

Most LR parsers just return an error, tree-sitter doesn't return an error but at least the rust-grammar as written doesn't recover many nodes (see example in the post). My *gut* feeling is that might be hard to do, as in LR error recovery what you typically do is anticipating error cases and writing explicit error productions, while the hand-written LL style does the opposite -- there are no explicit "and here we might see an incomplete nodes"  logic, everything is optional. So it's not as much as error-detection/error-recovery, as it is valid syntax detection. 

Would love to see LR parser that can do the above!

**Comment by cr1901** [comment]
To be clear: this thread is not meant to be a "fall vs LALRPOP" competition. I've just been talking to multiple ppl lately about "how to make a decent parser" and have been seeing what ideas work vs don't work. This is also me minddumping for later :):

My hotlist parser might be a bit "too simple" of a grammar, and I won't run into some roadblocks I would, say, parsing a full programming language. That said:

>Maybe you can, I just haven't seen this done in practice to a satisfactory level!
 
When I return to this project (this took me ~a week to get right, but I _started_ it in Nov 2019, because I'm horrible at finishing projects :P), I'm going to experiment w/ returning "out-of-band" errors based on convos w/ one person who has written a number of parsers.

>My gut feeling is that might be hard to do, as in LR error recovery what you typically do is anticipating error cases and writing explicit error productions

This is indeed what LALRPOP does, but you're free to do [whatever you want](http://lalrpop.github.io/lalrpop/tutorial/008_error_recovery.html) during an error production. Instead of ` => { errors.push(<>); Box::new(Expr::Error) }` and having explicit `Error` nodes in the AST, I would parse and return fake defaults, depending on what the error node "looks like" (which yes, _will_ be a guess/value judgment).
